import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import LandingContainer from "@/components/common/LandingContainer";
import Footer from "@/components/common/layout/footer";
import Navbar from "@/components/common/layout/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Unite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <div>{children}</div>
      <Footer />
    </>
  );
}
